version: '3.8'

services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6381:6379"
      - "8001:8001"
    volumes:
      - redisdata:/data
      - ./dump.rdb:/data/dump.rdb
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      FLASK_RUN_PORT: 5000
    volumes:
      - .:/app
      - ./data-gym-cache:/tmp
    depends_on:
      - redis
    restart: always

volumes:
  redisdata:
